"use client";

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import type { Product } from "@/data/products";

export type Locale = "uz" | "ru";

type Dictionary = Record<string, string>;

const uz: Dictionary = {
  home:"Bosh sahifa", shop:"Mahsulotlar", about:"Biz haqimizda", contact:"Aloqa", favorites:"Sevimlilar", profile:"Profil", cart:"Savatcha", search:"Qidirish", menu:"Menyu", language:"Til",
  heroEyebrow:"Har kuni qo‘lda tayyorlanadi", heroTitle:"Shirin lahzalar shu yerdan boshlanadi.", heroText:"Premium masalliqlardan mehr bilan tayyorlangan nafis tortlar, makaronlar va shirinliklar.", shopNow:"Xarid qilish", ourStory:"Bizning hikoyamiz", happyCustomers:"10 000+ mamnun mijoz",
  curated:"Siz uchun tanlangan", featuredTitle:"Har kuni yangi, har luqmada zavq.", featuredText:"Ipakdek cheesecake, nafis makaron va mayin shirinliklar — oddiy lahzani unutilmas qilish uchun.",
  explore:"Kolleksiyani ko‘rish", categoriesEyebrow:"Kolleksiyani o‘rganing", categoriesTitle:"O‘zingizga mos shirinlikni toping.", bestEyebrow:"Eng ko‘p sotilganlar", bestTitle:"Hamma sevib buyurtma qiladigan ta’mlar.",
  offerEyebrow:"Hafta oxiri kolleksiyasi", offerTitle:"Ichida kichik bayramlar yashiringan quti.", offerText:"Tanlangan sovg‘a qutilari va makaronlarga hafta oxirigacha 15% chegirma.",
  philosophy:"Bizning falsafamiz", philosophyTitle:"Sekin tayyorlanadi. Darhol seviladi.", philosophyText:"Sweetora — sifatli masalliqlar, kichik partiyalarda pishirish va chiroyli detallarni qadrlaydigan premium qandolat brendi.",
  kindWords:"Mijozlar fikri", kindTitle:"Shirinlikni sevuvchilar tanlovi.", instagram:"Shirinliklar lentangizda", newsletterEyebrow:"Yangiliklardan xabardor bo‘ling", newsletterTitle:"Yangi shirinliklardan birinchi bo‘lib xabardor bo‘ling.", newsletterText:"Yangi mahsulotlar, mavsumiy qutilar va maxsus takliflar emailingizga.", emailPlaceholder:"Email manzilingiz", subscribe:"Obuna bo‘lish",
  collection:"Kolleksiya", productsFound:"ta mahsulot", dessertsTitle:"Bahamlashishga arziydigan shirinliklar.", dessertsText:"Tortlar, makaronlar, pechenyelar va sovg‘alar — har biri mehr bilan tayyorlangan.", all:"Barchasi", featured:"Tavsiya etilgan", priceLow:"Narx: arzon", priceHigh:"Narx: qimmat", topRated:"Yuqori baholangan", noProducts:"Mahsulot topilmadi. Boshqa qidiruvni sinab ko‘ring.",
  productReviews:"ta sharh", addCart:"Savatchaga qo‘shish", buyNow:"Hozir xarid qilish", ingredients:"Masalliqlar", sizeWeight:"Hajm / og‘irlik", deliveryTitle:"Yangi yetkazib berish", deliveryText:"Tanlangan hududlarda shu kunning o‘zida yetkazib beriladi.", packedTitle:"Ehtiyotkor qadoqlash", packedText:"Himoyalangan va sovg‘aga tayyor qadoq.", related:"Sizga yana yoqishi mumkin",
  cartTitle:"Shirin savatcha.", cartEmptyTitle:"Savatchangiz biroz bo‘sh.", cartEmptyText:"Bir nechta chiroyli shirinlik qo‘shing va kuningizni yanada shirin qiling.", continueShopping:"Xaridni davom ettirish", summary:"Buyurtma xulosasi", subtotal:"Oraliq jami", delivery:"Yetkazib berish", free:"Bepul", total:"Jami", promo:"Promo kod", apply:"Qo‘llash", checkout:"Rasmiylashtirish",
  checkoutTitle:"Buyurtmani rasmiylashtirish", customerInfo:"Mijoz ma’lumotlari", fullName:"To‘liq ism", phone:"Telefon", city:"Shahar", address:"Manzil", apartment:"Xonadon / kvartira", deliveryDate:"Yetkazib berish sanasi", deliveryTime:"Yetkazib berish vaqti", payment:"To‘lov", cash:"Naqd", card:"Karta", online:"Onlayn", yourOrder:"Buyurtmangiz", placeOrder:"Buyurtma berish", orderReceived:"Buyurtma qabul qilindi.", orderThanks:"Rahmat. Shirinliklaringiz mehr bilan tayyorlanmoqda.", viewOrders:"Buyurtmalarni ko‘rish", emptyCheckout:"Hali rasmiylashtiriladigan buyurtma yo‘q.",
  account:"Sweetora akkaunti", welcome:"Xush kelibsiz.", loginText:"Sevimli shirinliklaringizni saqlash uchun tizimga kiring.", password:"Parol", remember:"Meni eslab qolish", forgot:"Parolni unutdingizmi?", login:"Kirish", google:"Google orqali davom etish", noAccount:"Akkauntingiz yo‘qmi?", register:"Ro‘yxatdan o‘tish", join:"Sweetora’ga qo‘shiling", createAccount:"Akkaunt yarating.", confirmPassword:"Parolni tasdiqlang", alreadyAccount:"Akkauntingiz bormi?", create:"Akkaunt yaratish",
  wishlist:"Istaklar ro‘yxati", wishlistTitle:"Sizning shirin ro‘yxatingiz.", nothingSaved:"Hali hech narsa saqlanmagan.", saveHint:"Yoqtirgan shirinliklaringizdagi yurak belgisini bosing.", exploreDesserts:"Shirinliklarni ko‘rish",
  accountLabel:"Akkaunt", ordersTitle:"Buyurtmalaringiz.", processing:"Jarayonda", preparing:"Tayyorlanmoqda", shipped:"Jo‘natildi", delivered:"Yetkazildi", cancelled:"Bekor qilindi", verified:"Tasdiqlangan mijoz",
  storyEyebrow:"Bizning hikoyamiz", storyTitle:"Bayram qilishning yanada nafis usuli.", storyText:"Sweetora oddiy fikrdan boshlangan: eng yaxshi shirinliklar odamlarni bir joyga yig‘adi va lahzani qadrlashga undaydi.", tasteCollection:"Kolleksiyani tatib ko‘ring", whyChoose:"Nega aynan biz", detailsTitle:"Kichik detallar katta farq qiladi.", premiumIngredients:"Premium masalliqlar", handmade:"Har kuni qo‘lda", freshDelivery:"Yangi yetkazib berish", giftPackaging:"Sovg‘aga tayyor qadoq", happy:"Mamnun mijozlar", creations:"Shirinliklar", years:"Yillik tajriba", positive:"Ijobiy sharhlar",
  sayHello:"Salom ayting", contactTitle:"Siz bilan bog‘lanishdan xursandmiz.", contactText:"Buyurtma, maxsus tort yoki shunchaki salomlashish uchun bizga yozing.", message:"Xabaringiz", send:"Xabar yuborish", workingHours:"Ish vaqti", everyDay:"Dush–Yak · 09:00–21:00", addressLabel:"Manzil", phoneLabel:"Telefon", emailLabel:"Email",
  exploreCollection:"Kolleksiyani ko‘rish", bestseller:"Eng ko‘p sotilgan", signature:"Signature", fresh:"Yangi", popular:"Mashhur", giftFavorite:"Sovg‘a uchun sevimli", seasonal:"Mavsumiy", verifiedCustomer:"Tasdiqlangan mijoz", orderItems1:"Pistali orzu torti × 1, Malinali makaron × 1", orderItems2:"Tuzli karamelli ponchik × 2, Brownie qutisi × 1", orderItems3:"Signature sovg‘a qutisi × 1", review1:"Pistali cheesecake juda mazali edi. Qadoqlash ham juda chiroyli.", review2:"Saytdan tortib birinchi luqmagacha hammasi premium tuyuladi.", review3:"Sovg‘a qutisi yangi va juda chiroyli yetib keldi."
};

const ru: Dictionary = {
  home:"Главная", shop:"Каталог", about:"О нас", contact:"Контакты", favorites:"Избранное", profile:"Профиль", cart:"Корзина", search:"Поиск", menu:"Меню", language:"Язык",
  heroEyebrow:"Готовим вручную каждый день", heroTitle:"Сладкие моменты начинаются здесь.", heroText:"Изысканные торты, макаронс и десерты из премиальных ингредиентов, приготовленные с любовью.", shopNow:"В каталог", ourStory:"Наша история", happyCustomers:"10 000+ довольных клиентов",
  curated:"Для вас", featuredTitle:"Свежие каждый день, восхитительные с первого кусочка.", featuredText:"Нежные чизкейки, изысканные макаронс и красивые десерты для особенных моментов.",
  explore:"Смотреть коллекцию", categoriesEyebrow:"Исследуйте коллекцию", categoriesTitle:"Найдите свой любимый десерт.", bestEyebrow:"Бестселлеры", bestTitle:"Вкусы, которые заказывают снова и снова.",
  offerEyebrow:"Коллекция выходных", offerTitle:"Коробка, внутри которой маленькие праздники.", offerText:"Скидка 15% на выбранные подарочные боксы и макарон до конца выходных.",
  philosophy:"Наша философия", philosophyTitle:"Готовим медленно. Любят сразу.", philosophyText:"Sweetora — премиальная кондитерская о честных ингредиентах, небольших партиях и красивых деталях.",
  kindWords:"Отзывы", kindTitle:"Любимые десерты наших гостей.", instagram:"Сладость в вашей ленте", newsletterEyebrow:"Будьте в курсе", newsletterTitle:"Узнавайте о новых десертах первыми.", newsletterText:"Новинки, сезонные боксы и специальные предложения — прямо на вашу почту.", emailPlaceholder:"Ваш email", subscribe:"Подписаться",
  collection:"Коллекция", productsFound:"товаров", dessertsTitle:"Десерты, которыми хочется делиться.", dessertsText:"Торты, макарон, печенье и подарки — каждый создан с заботой.", all:"Все", featured:"Рекомендуемые", priceLow:"Цена: по возрастанию", priceHigh:"Цена: по убыванию", topRated:"По рейтингу", noProducts:"Ничего не найдено. Попробуйте изменить запрос.",
  productReviews:"отзывов", addCart:"В корзину", buyNow:"Купить сейчас", ingredients:"Ингредиенты", sizeWeight:"Размер / вес", deliveryTitle:"Свежая доставка", deliveryText:"Доставка в выбранные районы в тот же день.", packedTitle:"Бережная упаковка", packedText:"Защищённая и готовая к подарку упаковка.", related:"Вам также понравится",
  cartTitle:"Сладкая корзина.", cartEmptyTitle:"Корзина пока пуста.", cartEmptyText:"Добавьте несколько красивых десертов и сделайте день слаще.", continueShopping:"Продолжить покупки", summary:"Итого заказа", subtotal:"Подытог", delivery:"Доставка", free:"Бесплатно", total:"Итого", promo:"Промокод", apply:"Применить", checkout:"Оформить заказ",
  checkoutTitle:"Оформление заказа", customerInfo:"Данные клиента", fullName:"Полное имя", phone:"Телефон", city:"Город", address:"Адрес", apartment:"Квартира", deliveryDate:"Дата доставки", deliveryTime:"Время доставки", payment:"Оплата", cash:"Наличные", card:"Карта", online:"Онлайн", yourOrder:"Ваш заказ", placeOrder:"Оформить заказ", orderReceived:"Заказ принят.", orderThanks:"Спасибо. Ваши десерты уже готовятся с заботой.", viewOrders:"Мои заказы", emptyCheckout:"Пока нечего оформлять.",
  account:"Аккаунт Sweetora", welcome:"С возвращением.", loginText:"Войдите, чтобы сохранить любимые десерты.", password:"Пароль", remember:"Запомнить меня", forgot:"Забыли пароль?", login:"Войти", google:"Продолжить через Google", noAccount:"Нет аккаунта?", register:"Регистрация", join:"Присоединяйтесь к Sweetora", createAccount:"Создайте аккаунт.", confirmPassword:"Подтвердите пароль", alreadyAccount:"Уже есть аккаунт?", create:"Создать аккаунт",
  wishlist:"Избранное", wishlistTitle:"Ваш список сладостей.", nothingSaved:"Пока ничего нет.", saveHint:"Нажимайте на сердечко у десертов, которые вам нравятся.", exploreDesserts:"Смотреть десерты",
  accountLabel:"Аккаунт", ordersTitle:"Ваши заказы.", processing:"В обработке", preparing:"Готовится", shipped:"Отправлен", delivered:"Доставлен", cancelled:"Отменён", verified:"Проверенный клиент",
  storyEyebrow:"Наша история", storyTitle:"Более красивый способ отмечать моменты.", storyText:"Sweetora началась с простой идеи: лучшие десерты собирают людей вместе и помогают ценить момент.", tasteCollection:"Попробовать коллекцию", whyChoose:"Почему мы", detailsTitle:"Маленькие детали имеют значение.", premiumIngredients:"Премиальные ингредиенты", handmade:"Ручная работа каждый день", freshDelivery:"Свежая доставка", giftPackaging:"Подарочная упаковка", happy:"Довольные клиенты", creations:"Десерты", years:"Лет мастерства", positive:"Положительных отзывов",
  sayHello:"Свяжитесь с нами", contactTitle:"Будем рады вас услышать.", contactText:"Вопрос по заказу, индивидуальный десерт или просто привет — напишите нам.", message:"Сообщение", send:"Отправить", workingHours:"Часы работы", everyDay:"Пн–Вс · 09:00–21:00", addressLabel:"Адрес", phoneLabel:"Телефон", emailLabel:"Email",
  exploreCollection:"Смотреть коллекцию", bestseller:"Бестселлер", signature:"Фирменный", fresh:"Новинка", popular:"Популярное", giftFavorite:"Любимый подарок", seasonal:"Сезонное", verifiedCustomer:"Проверенный клиент", orderItems1:"Фисташковый торт × 1, Малиновый макарон × 1", orderItems2:"Пончики с солёной карамелью × 2, Бокс брауни × 1", orderItems3:"Фирменный подарочный бокс × 1", review1:"Фисташковый чизкейк был невероятно вкусным. Упаковка тоже очень красивая.", review2:"Всё ощущается премиально — от сайта до первого кусочка.", review3:"Подарочный бокс приехал свежим и очень красивым."
};

export const productTranslations: Record<string, {uz:{name:string;description:string;category:string};ru:{name:string;description:string;category:string}}> = {
 "belgian-chocolate-cake":{uz:{name:"Belgiyacha shokoladli tort",description:"Belgiya shokoladi kremi va yaltiroq ganash bilan qatlamlangan chuqur shokoladli biskvit.",category:"Tortlar"},ru:{name:"Бельгийский шоколадный торт",description:"Шоколадный бисквит с кремом из бельгийского шоколада и глянцевым ганашем.",category:"Торты"}},
 "strawberry-cream-cake":{uz:{name:"Qulupnayli krem tort",description:"Yengil vanilli biskvit, yangi qulupnay va mayin ko‘pirtirilgan krem.",category:"Tortlar"},ru:{name:"Торт с клубникой и кремом",description:"Лёгкий ванильный бисквит, свежая клубника и воздушные сливки.",category:"Торты"}},
 "red-velvet":{uz:{name:"Velvet Rose torti",description:"Mayin kakao torti, krem-sir va nafis atirgul bezagi.",category:"Tortlar"},ru:{name:"Торт Velvet Rose",description:"Нежный какао-корж с крем-чизом и изящным розовым декором.",category:"Торты"}},
 "pistachio-dream":{uz:{name:"Pista orzusi torti",description:"Pista biskviti, qovurilgan pista pralinasi va vanilli krem.",category:"Tortlar"},ru:{name:"Фисташковый Dream Cake",description:"Фисташковый бисквит с пралине из обжаренной фисташки и ванильным кремом.",category:"Торты"}},
 "vanilla-cupcakes":{uz:{name:"Vanilli bulut kapkeyklari",description:"Mayin vanilli kapkeyklar ustida yengil krem.",category:"Kapkeyklar"},ru:{name:"Ванильные капкейки Cloud",description:"Нежные ванильные капкейки с воздушным кремом.",category:"Капкейки"}},
 "chocolate-cupcakes":{uz:{name:"Shokoladli fudge kapkeyklar",description:"Boy kakao ta’mi va silliq fudge kremli kapkeyklar.",category:"Kapkeyklar"},ru:{name:"Шоколадные капкейки Fudge",description:"Насыщенные какао-капкейки с гладким шоколадным кремом.",category:"Капкейки"}},
 "hazelnut-cookies":{uz:{name:"Funduk va dengiz tuzli pechenye",description:"Qovurilgan funduk va ozgina dengiz tuzi qo‘shilgan sariyog‘li pechenye.",category:"Pechenyelar"},ru:{name:"Печенье с фундуком и морской солью",description:"Сливочное печенье с обжаренным фундуком и морской солью.",category:"Печенье"}},
 "butter-cookies":{uz:{name:"Fransuzcha sariyog‘li pechenye",description:"Nozik vanil hidli, mayin va qarsildoq sariyog‘li pechenye.",category:"Pechenyelar"},ru:{name:"Французское сливочное печенье",description:"Хрустящее нежное печенье с тонким ароматом ванили.",category:"Печенье"}},
 "salted-caramel-donuts":{uz:{name:"Tuzli karamelli ponchiklar",description:"Karamel glazurasi va dengiz tuzi bilan qoplangan yumshoq briosh ponchiklar.",category:"Ponchiklar"},ru:{name:"Пончики с солёной карамелью",description:"Воздушные бриошь-пончики с карамельной глазурью и морской солью.",category:"Пончики"}},
 "berry-donuts":{uz:{name:"Rezavorli glazurali ponchiklar",description:"Yumshoq ponchiklar, rezavor glazurasi va quritilgan malina.",category:"Ponchiklar"},ru:{name:"Пончики с ягодной глазурью",description:"Мягкие пончики с ягодной глазурью и малиной.",category:"Пончики"}},
 "dark-truffles":{uz:{name:"Qora shokoladli trufellar",description:"Premium kakao bilan qoplangan ipakdek qora shokolad ganashi.",category:"Shokoladlar"},ru:{name:"Тёмные шоколадные трюфели",description:"Шёлковый ганаш из тёмного шоколада в премиальном какао.",category:"Шоколад"}},
 "caramel-pralines":{uz:{name:"Karamelli pralin qutisi",description:"Sariyog‘li karamelli pralin bilan to‘ldirilgan turli shokoladlar.",category:"Shokoladlar"},ru:{name:"Коробка карамельных пралине",description:"Ассорти шоколадных конфет с нежной карамельной начинкой.",category:"Шоколад"}},
 "raspberry-macarons":{uz:{name:"Malinali makaronlar",description:"Nozik bodom qobig‘i va yorqin malinali krem.",category:"Makaronlar"},ru:{name:"Малиновый макарон",description:"Нежные миндальные оболочки с ярким малиновым кремом.",category:"Макарон"}},
 "pistachio-macarons":{uz:{name:"Pistali makaronlar",description:"Qovurilgan pista kremli nafis makaronlar.",category:"Makaronlar"},ru:{name:"Фисташковый макарон",description:"Изысканные макарон с кремом из обжаренной фисташки.",category:"Макарон"}},
 "lemon-cheesecake":{uz:{name:"Limonli ipak cheesecake",description:"Kremdek cheesecake, limon kurdi va pechenye asosli qatlam.",category:"Cheesecake"},ru:{name:"Лимонный Silk Cheesecake",description:"Кремовый чизкейк с лимонным курдом и хрустящей крошкой.",category:"Чизкейки"}},
 "lotus-cheesecake":{uz:{name:"Karamelli pechenyeli cheesecake",description:"Ipakdek cheesecake, karamelli pechenye asosi va qarsildoq ustki qatlam.",category:"Cheesecake"},ru:{name:"Чизкейк с карамельным печеньем",description:"Нежный чизкейк с карамельной основой и хрустящим топпингом.",category:"Чизкейки"}},
 "signature-gift-box":{uz:{name:"Signature sovg‘a qutisi",description:"Makaron, trufel, pechenye va mini tortdan iborat tanlangan quti.",category:"Sovg‘a qutilari"},ru:{name:"Фирменный подарочный бокс",description:"Коллекция макарон, трюфелей, печенья и мини-торта.",category:"Подарочные боксы"}},
 "mini-dessert-box":{uz:{name:"Mini dessert qutisi",description:"Bahamlashish yoki o‘zingizga qoldirish uchun nafis shirinliklar to‘plami.",category:"Sovg‘a qutilari"},ru:{name:"Мини-бокс десертов",description:"Элегантный набор десертов для компании или только для себя.",category:"Подарочные боксы"}},
 "strawberry-tart":{uz:{name:"Qulupnayli vanil tart",description:"Qarsildoq xamir, vanilli krem va yangi qulupnay.",category:"Tortlar"},ru:{name:"Клубнично-ванильный тарт",description:"Хрустящая основа с ванильным кремом и свежей клубникой.",category:"Торты"}},
 "matcha-bites":{uz:{name:"Matcha va oq shokolad bo‘laklari",description:"Xushbo‘y yapon matchasi va pista qo‘shilgan oq shokolad.",category:"Shokoladlar"},ru:{name:"Белый шоколад с матча",description:"Белый шоколад с ароматным японским матча и фисташкой.",category:"Шоколад"}},
 "berry-pavlova":{uz:{name:"Rezavorli Pavlova",description:"Qarsildoq beze, vanilli krem va mavsumiy rezavorlar.",category:"Tortlar"},ru:{name:"Ягодная Павлова",description:"Хрустящая меренга, ванильный крем и сезонные ягоды.",category:"Торты"}}
};


const ingredientMap:Record<string,{uz:string;ru:string}>={Cocoa:{uz:"Kakao",ru:"Kakao"},"Belgian dark chocolate":{uz:"Belgiya qora shokoladi",ru:"Бельгийский тёмный шоколад"},Butter:{uz:"Sariyog‘",ru:"Сливочное масло"},Cream:{uz:"Krem",ru:"Сливки"},Eggs:{uz:"Tuxum",ru:"Яйцо"},Vanilla:{uz:"Vanil",ru:"Ваниль"},Strawberries:{uz:"Qulupnay",ru:"Клубника"},"Cream cheese":{uz:"Krem-sir",ru:"Сливочный сыр"},Pistachio:{uz:"Pista",ru:"Фисташка"},Almond:{uz:"Bodom",ru:"Миндаль"},Hazelnut:{uz:"Funduk",ru:"Фундук"},"Sea salt":{uz:"Dengiz tuzi",ru:"Морская соль"},Caramel:{uz:"Karamel",ru:"Карамель"},Chocolate:{uz:"Shokolad",ru:"Шоколад"},Raspberry:{uz:"Malina",ru:"Малина"},"Egg whites":{uz:"Tuxum oqi",ru:"Белок"},Sugar:{uz:"Shakar",ru:"Сахар"},Lemon:{uz:"Limon",ru:"Лимон"},Biscuit:{uz:"Pechenye",ru:"Печенье"},"Dark chocolate":{uz:"Qora shokolad",ru:"Тёмный шоколад"},Cocoa:{uz:"Kakao",ru:"Какао"},"White chocolate":{uz:"Oq shokolad",ru:"Белый шоколад"},Matcha:{uz:"Matcha",ru:"Матча"},"Assorted premium desserts":{uz:"Tanlangan premium shirinliklar",ru:"Ассорти премиальных десертов"},"Assorted desserts":{uz:"Turli shirinliklar",ru:"Ассорти десертов"},Flour:{uz:"Un",ru:"Мука"}};

const categoryMap:Record<string,{uz:string;ru:string}>={Cakes:{uz:"Tortlar",ru:"Торты"},Cupcakes:{uz:"Kapkeyklar",ru:"Капкейки"},Cookies:{uz:"Pechenyelar",ru:"Печенье"},Donuts:{uz:"Ponchiklar",ru:"Пончики"},Chocolates:{uz:"Shokoladlar",ru:"Шоколад"},Macarons:{uz:"Makaronlar",ru:"Макарон"},Cheesecakes:{uz:"Cheesecake",ru:"Чизкейки"},"Gift Boxes":{uz:"Sovg‘a qutilari",ru:"Подарочные боксы"}};

export function I18nProvider({children}:{children:ReactNode}){
 const [locale,setLocale]=useState<Locale>("uz");
 useEffect(()=>{const saved=localStorage.getItem("sweetora-locale") as Locale|null;if(saved==="uz"||saved==="ru")setLocale(saved);},[]);
 useEffect(()=>{localStorage.setItem("sweetora-locale",locale);document.documentElement.lang=locale;},[locale]);
 const value=useMemo(()=>({locale,setLocale,t:(key:string)=> (locale==="uz"?uz:ru)[key] ?? key, category:(key:string)=>categoryMap[key]?.[locale]??key, product:(p:Product)=>productTranslations[p.id]?.[locale]??{name:p.name,description:p.description,category:categoryMap[p.category]?.[locale]??p.category}}),[locale]);
 return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
type I18nValue = { locale: Locale; setLocale: (locale: Locale) => void; t: (key: string) => string; category: (key: string) => string; ingredient: (key: string) => string; product: (product: Product) => {name:string;description:string;category:string} };
const I18nContext=createContext<I18nValue|null>(null);
export function useI18n(){const value=useContext(I18nContext);if(!value)throw new Error("useI18n must be used inside I18nProvider");return value;}
